### ISSUE TITLE
mdb init Pro problem

### ISSUE THREAD

**Issue by xvMODvx** [mdbootstrap/mdb-cli#1]
When typing mdb list all the products are listed as available. When running mdb init all the Pro versions give the same error response:

```
$ mdb init
? Choose project to initialize jquery-ui-kit
Initializing...
[========================================================================] 0.0 s


? Missing package.json file. Create? Yes
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'init', '--yes' ]
}

```
While all the non Pro options work correctly displaying:
```
mdb init
? Choose project to initialize bootstrap-material-design
Initializing...
Cloning into 'bootstrap-material-design'...

┌─────────┬────────┬─────────────────────────────┐
│ (index) │ Status │           Message           │
├─────────┼────────┼─────────────────────────────┤
│    0    │   0    │ 'Initialization completed.' │
└─────────┴────────┴─────────────────────────────┘
```

**Comment by catchmareck** [comment]
What environment do you use? I mean OS, Node/npm version etc

**Comment by catchmareck** [comment]
I'm closing this issue since it's been inactive for over a month.
